### ISSUE TITLE
How to properly group a player on spawn?

### ISSUE THREAD

**Issue by mwalk-dev** [hudmarc/FFO-FishNet-Floating-Origin#2]
I'm using Unity 2021.3.19f1, FishNet Pro 2.6.7, and FO 0.0.6. I've followed your setup in #1 (thank you for that, btw!). My issue is that when the `PlayerSpawner` spawns multiple players at the origin, they're put into separate scenes and groups. If they spread out enough to rebase the origin and then move closer together again, FO works fine. It's just not grouping them when they spawn close together.

I tried to use `FOManager.instance.TeleportTo(FOObserver, Vector3d)` from `OnStartServer` when a player spawns, but that causes a NRE on [FOManager.cs](https://github.com/hudmarc/FFO-FishNet-Floating-Origin/blob/main/Runtime/FOManager.cs#L185) because the observer isn't yet in a group. I might be missing something obvious, but what's the correct way to handle this?

**Comment by hudmarc** [comment]
Are all the players being spawned at once on the server? During testing I was always spawning players on join, so I don't think I ever accounted for all players being spawned at the same time... however they should be placed in the same offset group regardless, I'll check the code and get back to you.

**Comment by hudmarc** [comment]
For the first ~6 frames none of the Observers have an assigned Offset Group yet, so that would explain why calling `FOManager.instance.TeleportTo` in `OnStartServer` wouldn't work.

**Comment by mwalk-dev** [comment]
Thanks for checking. I am joining from multiple clients with the `NetworkManager` prefab's HUD, so the joins are staggered. I updated my code to avoid the NRE when teleporting, but unfortunately teleporting in general didn't solve the original issue of clients spawning at the same position being put in different scenes.

Here is how I've configured my player and `NetworkManager`, for reference:
![image](https://user-images.githubusercontent.com/24628430/220609846-1ab756a0-23e3-453a-b4e6-3c28e6893dde.png)
![image](https://user-images.githubusercontent.com/24628430/220610400-6e1e5ff9-0f69-4b32-aabb-813dd197fb77.png)

And the result that I'm seeing:
![image](https://user-images.githubusercontent.com/24628430/220612432-7bedeb6a-98bf-4658-97c3-0f9c4fe0a7cd.png)

**Comment by hudmarc** [comment]
Try the latest version. I think I know what was causing the bug. Let me know if it works as intended now.

**Comment by hudmarc** [comment]
Also, note you need an enabled FODebugger on your player(s) now in order to see the floating origin debug in the new version.

**Comment by mwalk-dev** [comment]
I grabbed the latest and added the FODebugger, but I'm still seeing the same behavior.

**Comment by mwalk-dev** [comment]
I don't know exactly where the problem is, but with some further testing this appears to specifically be an issue with spawning at the Unity origin. I changed my player prefab's position to something other than the origin and then players get grouped properly on spawn.

**Comment by hudmarc** [comment]
that's bizarre... if you change the players back to the origin position does it still work? what exactly did you change, the spawn position of the players? Or the position of the spawn point?

**Comment by mwalk-dev** [comment]
I didn't actually set any spawn points in my `PlayerSpawner`, so it was just spawning them at the prefab's transform position, which was (0,0,0). In that scenario, the players aren't getting grouped correctly. If the player prefab's transform position is something other than (0,0,0) then it works.

I kind of suspect there might be something that can't distinguish between a default vector struct value of (0,0,0) and something that is intentionally (0,0,0)? Just a wild guess.

**Comment by hudmarc** [comment]
That's bizarre. Nowhere in the code is Vector3.Zero assumed to be a "null" value. I just uploaded a new version `0.7b`, this one has an exposed `RebuildOffsetGroup(FOObserver observer)` method which you can call on an Observer if you think it was grouped incorrectly. However this should never happen, and if it continues to happen please let me know.

**Comment by hudmarc** [comment]
Are you still encountering this issue or is it working properly now?

**Comment by mwalk-dev** [comment]
I am still having this problem. I haven't had time to step through the code and identify where it's going wrong, but I can summarize what I've found so far, using a chunkSize of 512 and a FN PlayerSpawner that doesn't have spawn areas set.

- [CORRECT] Host spawns at Unity position (0,0,0) regardless of player prefab’s position. FO Debugger-reported real position and group offset reflect the player prefab’s position
- [BUG] Client spawns at Unity position == player prefab’s position, with real position by an additional player prefab’s position. E.g. with player prefab at (50, 0, 0) the client spawns at (50, 0, 0) Unity with a real position of (100, 0, 0). I'd expect the client's real position to be the same as the host's, since it's the same prefab.
- [BUG] As long as |host real pos - client real pos| < 0.5 * chunk size, the two are incorrectly put in separate groups despite being close enough that they should be in a single chunk. As soon as that condition isn’t true, the host and client get correctly put into a single group. E.g. with chunk size == 512:
   - If player prefab has position (255, 0, 0) then the host is at unity (0, 0, 0) and real (255, 0, 0). Client is at unity (255, 0, 0) and real (510, 0, 0) and the two are in separate groups. This is an incorrect position, but even then they're closer than the 512 chunk size so they should be in a single group.
   - If player prefab has position (256, 0, 0) then the host and client both get placed at real (256, 0, 0) in a single group which is correct.

I will try to share a simple project that demonstrates the issue when I'm able.

**Comment by hudmarc** [comment]
So clients are not being spawned at the origin? iirc the code assumes all clients will spawn at the origin and then be teleported wherever they need to go

**Comment by hudmarc** [comment]
Yes, if you can forward a demonstration of the bug that would be great. I suspect the problem is in the RegisterObserver method in the FOManager.

**Comment by mwalk-dev** [comment]
I've exported my test project as a unity package. If there's a better way to share it, let me know. I can reproduce by:

1. Create an empty 3D Project (I used 2021.3.20f1)
2. Unzip [fishnet_fo_example.zip](https://github.com/hudmarc/FFO-FishNet-Floating-Origin/files/10943245/fishnet_fo_example.zip) and import the unitypackage
3. Add the FO package from the git URL
4. Add offline and online scenes to the build and build the code
5. Run in editor as host and connect with the built player as client

**Comment by hudmarc** [comment]
Thanks for the test package! I'll take a look at it.

**Comment by hudmarc** [comment]
Ok, version 0.1.0 addresses the problems seen here. Also, the reason your player was flying away is because the two raycasts in the default player component use Physics.Raycast, make sure to use the scene-specific version of the Raycast code. Here is the modified script, which uses the correct raycast.

```
using FishNet.Connection;
using FishNet.Object;
using UnityEngine;

namespace FishNet.Example.Scened
{


    public class PlayerController : NetworkBehaviour
    {
        [SerializeField]
        private GameObject _camera;
        [SerializeField]
        private float _moveRate = 4f;
        [SerializeField]
        private bool _clientAuth = true;

        public override void OnStartClient()
        {
            base.OnStartClient();
            if (base.IsOwner)
                _camera.SetActive(true);
        }

        private void Update()
        {
            if (!base.IsOwner)
                return;

            float hor = Input.GetAxisRaw("Horizontal");
            float ver = Input.GetAxisRaw("Vertical");

            /* If ground cannot be found for 20 units then bump up 3 units. 
             * This is just to keep player on ground if they fall through
             * when changing scenes.             */
            if (_clientAuth || (!_clientAuth && base.IsServer))
            {
                if (!gameObject.scene.GetPhysicsScene().Raycast(transform.position + new Vector3(0f, 0.3f, 0f), Vector3.down, 20))
                    transform.position += new Vector3(0f, 3f, 0f);
            }

            if (_clientAuth)
                Move(hor, ver);
            else
                ServerMove(hor, ver);
        }

        [ServerRpc]
        private void ServerMove(float hor, float ver)
        {
            Move(hor, ver);
        }

        private void Move(float hor, float ver)
        {
            float gravity = -10f * Time.deltaTime;
            //If ray hits floor then cancel gravity.
            Ray ray = new Ray(transform.position + new Vector3(0f, 0.05f, 0f), -Vector3.up);
            if (gameObject.scene.GetPhysicsScene().Raycast(transform.position + new Vector3(0f, 0.05f, 0f), Vector3.down, 0.1f + -gravity))
                gravity = 0f;

            /* Moving. */
            Vector3 direction = new Vector3(
                0f,
                gravity,
                ver * _moveRate * Time.deltaTime);

            transform.position += transform.TransformDirection(direction);
            transform.Rotate(new Vector3(0f, hor * 100f * Time.deltaTime, 0f));
        }

    }


}


```

**Comment by hudmarc** [comment]
Ok, version 0.1.0 addresses the problems seen here. Also, the reason your player was flying away is because the two raycasts in the default player component use Physics.Raycast, make sure to use the scene-specific version of the Raycast code. Here is the modified script, which uses the correct raycast.

```
using FishNet.Connection;
using FishNet.Object;
using UnityEngine;

namespace FishNet.Example.Scened
{


    public class PlayerController : NetworkBehaviour
    {
        [SerializeField]
        private GameObject _camera;
        [SerializeField]
        private float _moveRate = 4f;
        [SerializeField]
        private bool _clientAuth = true;

        public override void OnStartClient()
        {
            base.OnStartClient();
            if (base.IsOwner)
                _camera.SetActive(true);
        }

        private void Update()
        {
            if (!base.IsOwner)
                return;

            float hor = Input.GetAxisRaw("Horizontal");
            float ver = Input.GetAxisRaw("Vertical");

            /* If ground cannot be found for 20 units then bump up 3 units. 
             * This is just to keep player on ground if they fall through
             * when changing scenes.             */
            if (_clientAuth || (!_clientAuth && base.IsServer))
            {
                if (!gameObject.scene.GetPhysicsScene().Raycast(transform.position + new Vector3(0f, 0.3f, 0f), Vector3.down, 20))
                    transform.position += new Vector3(0f, 3f, 0f);
            }

            if (_clientAuth)
                Move(hor, ver);
            else
                ServerMove(hor, ver);
        }

        [ServerRpc]
        private void ServerMove(float hor, float ver)
        {
            Move(hor, ver);
        }

        private void Move(float hor, float ver)
        {
            float gravity = -10f * Time.deltaTime;
            //If ray hits floor then cancel gravity.
            Ray ray = new Ray(transform.position + new Vector3(0f, 0.05f, 0f), -Vector3.up);
            if (gameObject.scene.GetPhysicsScene().Raycast(transform.position + new Vector3(0f, 0.05f, 0f), Vector3.down, 0.1f + -gravity))
                gravity = 0f;

            /* Moving. */
            Vector3 direction = new Vector3(
                0f,
                gravity,
                ver * _moveRate * Time.deltaTime);

            transform.position += transform.TransformDirection(direction);
            transform.Rotate(new Vector3(0f, hor * 100f * Time.deltaTime, 0f));
        }

    }


}
```

**Comment by hudmarc** [comment]
If there are any further issues please do not hesitate to report them here, or open a new issue.

**Comment by mwalk-dev** [comment]
I've updated to v0.1.0 in my test project and it appears to be working perfectly! It will take some more time before I'm able to update my main project, but I don't see a reason to keep this open for now.
